Detect csvkit more conventionally
Checking for a source distrib of csvkit locks the user into installing
in just one way, and a non-standard way at that.  Instead, we just see
if the utilities are available and if the version string works.  We
don't even check the number on the version string because older
versions don't actually support --version.  If it doesn't error, it's
new enough.

Also, I removed the virtualenv stuff in the script.  This isn't the
place to force the user to use virtualenv.  If the user wants to use
virtualenv, the right place to do it is *before* the user runs
wiki-refresh.  That way the user gets to set their environment, which
is the whole point of virtualenv.  In my case, for example, I just did
a `pip install csvkit` in my Macfound virtualenv.  It made the tools
available while that virtualenv was active, and that was good enough
to make it available to wiki-refresh.

diff --git a/wiki-refresh b/wiki-refresh
--- a/wiki-refresh
+++ b/wiki-refresh
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # Load all the 100&Change proposals into a wiki.
 #
@@ -32,6 +32,13 @@ MACFOUND_DIR=`dirname "${0}"`
 SOURCES_ROOT="${MACFOUND_DIR}/.."
 CSVKIT_DIR="${SOURCES_ROOT}/csvkit"
 DATA_DIR="${1}"
+
+
+function check_for_bin {
+	command -v $1 >/dev/null 2>&1 || { echo >&2 "$1 required but it's not available.  Aborting."; exit 1; }
+}
+
+
 if [ "${DATA_DIR}" = "" ]; then
   echo "ERROR: DATA_DIRECTORY argument required."
   echo ""
@@ -42,18 +49,9 @@ if [ "${DATA_DIR}" = "" ]; then
   exit 1
 fi
 
-# Make sure we have csvkit.
-if [ ! -d "${CSVKIT_DIR}" ]; then
-  echo "ERROR: csvkit source tree not found."
-  echo ""
-  echo "Please do this..."
-  echo ""
-  echo "  $ cd $(dirname ${CSVKIT_DIR})"
-  echo "  $ git clone git@github.com:wireservice/csvkit.git"
-  echo ""
-  echo "...and then try again."
-  exit 1
-fi
+# Make sure we have csvkit by checking version on csvgrep.
+check_for_bin csvgrep
+csvgrep --version 2&>/dev/null || { echo "csvkit needs to be a recent version. Please upgrade to version 1.0.2+"; exit 1; }
 
 # Make sure we have csv2wiki.
 CSV2WIKI="${SOURCES_ROOT}/csv2wiki/csv2wiki"
@@ -249,10 +247,8 @@ echo ""
 
 # Filter out excluded Review Numbers.
 echo "Stage 2: Filtering excluded Review Numbers..."
-. ${CSVKIT_DIR}/VIRTUAL/bin/activate
 csvgrep -c 15 -f "${DATA_DIR}"/excluded-review-numbers.txt -i \
         "${DATA_DIR}"/${STAGE_1_CSV} > "${DATA_DIR}"/"${STAGE_2_CSV}"
-deactivate
 echo "Done with Stage 2 (filtering excluded Review Numbers)."
 echo ""
 
