Update 100Change2020 to handle decrypting
Before, this was handled manually, but in the new world, we script it
all from inside the ETL pipelines.  This adds that capability to the
2020 competition.

diff --git a/100Change2020/etl/deploy b/100Change2020/etl/deploy
--- a/100Change2020/etl/deploy
+++ b/100Change2020/etl/deploy
@@ -28,23 +28,21 @@
 #                                                                        #
 ##########################################################################
 
+COMPETITION="100Change2020"
 MACFOUND_DIR=`dirname "${0}"`
-DATA_DIR="${1}"
+BASE_DATA_DIR="${1}"
 
-if [ "${DATA_DIR}" = "" ]; then
-    BIGDATA_PATH="clients/macfound/eval-system/lever-for-change/data/bigdata"
-    [ -d "${OTSDIR}/${BIGDATA_PATH}" ] && DATA_DIR="${OTSDIR}/${BIGDATA_PATH}"
-fi
-
-if [ "${DATA_DIR}" = "" ]; then
-  echo "ERROR: DATA_DIRECTORY argument required."
+if [ "${BASE_DATA_DIR}" = "" ]; then
+  echo "ERROR: BASE_DATA_DIRECTORY argument required."
   echo ""
-  echo "Usage: '${0} DATA_DIRECTORY'"
+  echo "Usage: '${0} BASE_DATA_DIRECTORY'"
   echo ""
-  echo "(DATA_DIRECTORY is where all the .csv files are.)"
+  echo "BASE_DATA_DIRECTORY/100Change2020 is where all the work is done."
   echo ""
   exit 1
 fi
+
+DATA_DIR="${BASE_DATA_DIR}/${COMPETITION}"
 
 # Make sure we have python3
 python3 -V > /dev/null 2>&1 || { echo "python3 required, aborting" ; exit 1; }
@@ -55,16 +53,95 @@ JUDGE_EVALUATION_CSV="P2P-review-data-20190929-for-OTS-copy-fixed-by-OTS.csv"
 WISEHEAD_EVALUATION_CSV="100&Change_Wise_Head_Review_data_anon_judges_11162019.csv"
 REGIONCONFIG_CSV="regionconfig.csv"
 ATTACHMENTS_DIR="${DATA_DIR}/attachments"
+TMP_ATTACHMENTS_DIR="${DATA_DIR}/tmpattachments"
+BASE_ATTACHMENTS="Pdfs-and-Submission-Deadline-exports.zip"
+TECH_REVIEW_ATTACHMENTS="Tech_Review_PDFs.zip"
+FACTSHEET_ATTACHMENTS="Two-page_Factsheets.zip"
 SDGCONFIG_CSV="sdgconfig.csv"
 CANDID_CORRECTION_FILE="Candid_Application_Data_Clean_for_OTS_2020_01_13_01.csv"
 OTS_CORRECTION_FILE="OTS_Corrections.csv"
 OTS_METADATA="OTS_Metadata.csv"
+
 TOC_DIR="${DATA_DIR}/tocs"
 TDC_CONFIG_DIR="${DATA_DIR}/tdcconfig"
-CSV2WIKI_CONFIG="${MACFOUND_DIR}"/macfound-torquedata-csv2wiki-config
 OUTPUT_CSV="2019-processed.csv"
+CSV2WIKI_CONFIG="${MACFOUND_DIR}"/csv2wiki-config
 COMPOSER="${MACFOUND_DIR}"/compose-csvs
 UPLOADER="${MACFOUND_DIR}"/upload-csv
+
+if [ ! -f "${CSV2WIKI_CONFIG}" ]; then
+  echo "ERROR: No csv2wiki-config file found."
+  echo ""
+  echo "Try doing 'cp csv2wiki-config.tmpl csv2wiki-config' and"
+  echo "then editing csv2wiki-config as needed."
+  echo ""
+  exit 1
+fi
+
+if [ ! -d "${DATA_DIR}" ] ; then
+  echo "Stage 0: Setting up data directory..."
+
+  if [ "${OTSDIR}" = "" ] ; then
+    echo "ERROR: \$OTSDIR is not set up"
+    echo ""
+    echo "See bureaucracy/onboarding about setting the OTSDIR environment variable up"
+    exit 1
+  fi
+
+  ENCRYPTED_DIR="${OTSDIR}/clients/macfound/torque-sites/${COMPETITION}/data/bigdata"
+  if [ ! -d "${ENCRYPTED_DIR}" ] ; then
+    echo "ERROR: it looks like your encrypted dir isn't checked out"
+    echo ""
+    echo "It was expected to be in:"
+    echo "  $ENCRYPTED_DIR"
+    echo ""
+    echo "You will need to check out the subversion torque-sites data, and then"
+    echo "run get-bigdata from ${OTSDIR}/clients/macfound/torque-sites/${COMPETITION}/data/"
+    exit 1
+  fi
+
+  mkdir -p $DATA_DIR
+  echo "Decrypting..."
+
+  gpg -o ${DATA_DIR}/${PROPOSALS_CSV} --decrypt ${ENCRYPTED_DIR}/${PROPOSALS_CSV}.asc || exit 1
+  gpg -o ${DATA_DIR}/${ADMIN_REVIEW_CSV} --decrypt ${ENCRYPTED_DIR}/${ADMIN_REVIEW_CSV}.asc || exit 1
+  gpg -o ${DATA_DIR}/${JUDGE_EVALUATION_CSV} --decrypt ${ENCRYPTED_DIR}/${JUDGE_EVALUATION_CSV}.asc || exit 1
+  gpg -o ${DATA_DIR}/${WISEHEAD_EVALUATION_CSV} --decrypt ${ENCRYPTED_DIR}/${WISEHEAD_EVALUATION_CSV}.asc || exit 1
+  gpg -o ${DATA_DIR}/${CANDID_CORRECTION_FILE} --decrypt ${ENCRYPTED_DIR}/${CANDID_CORRECTION_FILE}.asc || exit 1
+  gpg -o ${DATA_DIR}/${OTS_CORRECTION_FILE} --decrypt ${ENCRYPTED_DIR}/${OTS_CORRECTION_FILE}.asc || exit 1
+  gpg -o ${DATA_DIR}/${OTS_METADATA} --decrypt ${ENCRYPTED_DIR}/${OTS_METADATA}.asc || exit 1
+  gpg -o ${DATA_DIR}/${BASE_ATTACHMENTS} --decrypt ${ENCRYPTED_DIR}/${BASE_ATTACHMENTS}.asc || exit 1
+  gpg -o ${DATA_DIR}/${TECH_REVIEW_ATTACHMENTS} --decrypt ${ENCRYPTED_DIR}/${TECH_REVIEW_ATTACHMENTS}.asc || exit 1
+  gpg -o ${DATA_DIR}/${FACTSHEET_ATTACHMENTS} --decrypt ${ENCRYPTED_DIR}/${FACTSHEET_ATTACHMENTS}.asc || exit 1
+
+  mkdir -p ${TOC_DIR}
+  mkdir -p ${ATTACHMENTS_DIR}
+  mkdir -p ${TDC_CONFIG_DIR}
+
+  echo "Setting up attachments..."
+  unzip -d $ATTACHMENTS_DIR ${DATA_DIR}/${BASE_ATTACHMENTS} 
+
+  mkdir -p $TMP_ATTACHMENTS_DIR
+  unzip -d $TMP_ATTACHMENTS_DIR ${DATA_DIR}/${TECH_REVIEW_ATTACHMENTS}
+  ls $TMP_ATTACHMENTS_DIR | grep "[[:digit:]]\+_" | while read file ; do
+    cp -v $TMP_ATTACHMENTS_DIR/$file ${ATTACHMENTS_DIR}/${file/_*/} ;
+  done
+  rm -rf $TMP_ATTACHMENTS_DIR
+
+  mkdir -p $TMP_ATTACHMENTS_DIR
+  unzip -d $TMP_ATTACHMENTS_DIR ${DATA_DIR}/${FACTSHEET_ATTACHMENTS}
+  ls $TMP_ATTACHMENTS_DIR | grep "_[[:digit:]]\+.pdf$" | while read file ; do
+    NUM=${file/*_/};
+    NUM=${NUM/.pdf/};
+    cp -v $TMP_ATTACHMENTS_DIR/$file ${ATTACHMENTS_DIR}/$NUM/;
+  done
+  rm -rf $TMP_ATTACHMENTS_DIR
+
+  # Clean up large zips to save disk space
+  rm ${DATA_DIR}/${BASE_ATTACHMENTS}
+  rm ${DATA_DIR}/${TECH_REVIEW_ATTACHMENTS}
+  rm ${DATA_DIR}/${FACTSHEET_ATTACHMENTS}
+fi
 
 if ! echo "bad31bbabd6b03ec5be834d3d87ec70361e8efa0  $DATA_DIR/$PROPOSALS_CSV" | sha1sum -c &> /dev/null ; then
   echo "ERROR: SHA of PROPOSALS_CSV did not match expectation!"
