Add extra ECW2020 Application Data

diff --git a/competitions/ECW2020/etl/deploy b/competitions/ECW2020/etl/deploy
--- a/competitions/ECW2020/etl/deploy
+++ b/competitions/ECW2020/etl/deploy
@@ -54,9 +54,12 @@ DATA_DIR="${BASE_DATA_DIR}/${COMPETITION}"
 # Make sure we have python3
 python3 -V > /dev/null 2>&1 || { echo "python3 required, aborting" ; exit 1; }
 
+command -v xlsx2csv 2>&1 >> /dev/null || { echo >&2 "xlsx2csv required but it's not available.  Aborting."; exit 1; }
+
 PROPOSALS_CSV="ECWC_Registration_Application_data.csv"
 BASE_ATTACHMENTS="Shane Eggerman - ECWC_Registration_Application_datа copy 2.zip"
 JUDGE_EVALUATION_CSV="Shane Eggerman - ECWC_Peer_Review_Data copy.csv"
+APPLICATION_DATA="ECW Application Data.xlsx"
 ATTACHMENTS_DIR="${DATA_DIR}/attachments/"
 TMP_ATTACHMENTS_DIR="${DATA_DIR}/tmpattachments"
 TDC_CONFIG_DIR="${DATA_DIR}/tdcconfig"
@@ -88,7 +91,10 @@ if [ ! -d "${DATA_DIR}" ] ; then
   echo "Decrypting..."
 
   gpg -o "${DATA_DIR}/${JUDGE_EVALUATION_CSV}" --decrypt "${ENCRYPTED_DIR}/${JUDGE_EVALUATION_CSV}.gpg" || exit 1
+  gpg -o "${DATA_DIR}/${APPLICATION_DATA}" --decrypt "${ENCRYPTED_DIR}/${APPLICATION_DATA}.gpg" || exit 1
   gpg -o "${DATA_DIR}/${BASE_ATTACHMENTS}" --decrypt "${ENCRYPTED_DIR}/${BASE_ATTACHMENTS}.gpg" || exit 1
+
+  xlsx2csv "$DATA_DIR/$APPLICATION_DATA" > "$DATA_DIR/${APPLICATION_DATA/xlsx/csv}"
 
   mkdir -p ${TDC_CONFIG_DIR}
 
@@ -118,6 +124,7 @@ mkdir -p $TDC_CONFIG_DIR
 ${RUNNER} --proposals-csv="${DATA_DIR}/${PROPOSALS_CSV}" \
           --attachments-dir=${ATTACHMENTS_DIR} \
           --judge-evaluation-csv="${DATA_DIR}/${JUDGE_EVALUATION_CSV}" \
+          --application-data="${DATA_DIR}/${APPLICATION_DATA/xlsx/csv}" \
           $PARE \
           $CSV_ONLY \
           --tdc-config-dir="${TDC_CONFIG_DIR}"
